name: Build Artifact & Push Image

on: 
  push: 
    branches: ["main"]

jobs: 
  build-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn clean package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/hygenec2olkid/test_backend_java_bbl:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Argo CD
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login Argo CD
        run: |
          argocd login ${{secrets.ARGOCD_SERVER}} \
            --username ${{secrets.ARGOCD_USERNAME}} \
            --password ${{secrets.ARGOCD_PASSWORD}} \
            --insecure

      - name: Trigger Argo CD sync image
        run: |
          argocd app sync test-backend
          argocd app wait test-backend
