name: Build Artifact & Push Image

on: 
  push: 
    branches: ["main"]
  pull-request:

job: 
  build:
    run-on: ubuntu-lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn clean package
